"""Base Strategy Protocol, Point-in-Time Context, and Abstract Interface."""
import abc
from dataclasses import dataclass
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Callable, Sequence
import uuid

from app.domains.backtest.data_feed import HistoricalBar, PointInTimeDataFeed
from app.domains.strategies.enums import (
    MarketRegime,
    SignalDirection,
    SignalType,
    StrategyCategory,
)
from app.domains.strategies.exceptions import (
    InvalidStrategyParameterError,
    StrategyLookAheadBiasError,
)
from app.domains.strategies.schemas import StrategyMetadata, TradingSignal


@dataclass
class StrategyContext:
    """Point-in-time strictly guarded context provided to strategies.

    Strategies can inspect current cash, equity, position quantities,
    and historical bars up to current_time. Any attempt to access data
    beyond current_time is strictly forbidden.
    """
    portfolio_id: uuid.UUID
    current_time: datetime
    cash_balance: Decimal
    current_equity: Decimal
    positions: dict[uuid.UUID, Decimal]  # instrument_id -> quantity
    data_feed: PointInTimeDataFeed

    def get_history(self, instrument_id: uuid.UUID, lookback_bars: int) -> list[HistoricalBar]:
        """Fetch historical bars up to current point-in-time clock."""
        history = self.data_feed.get_history(instrument_id, lookback_bars=lookback_bars)
        # Verify point-in-time invariant
        for bar in history:
            if bar.timestamp > self.current_time:
                raise StrategyLookAheadBiasError(
                    requested_time=bar.timestamp.isoformat(),
                    current_time=self.current_time.isoformat(),
                )
        return history

    def get_current_position(self, instrument_id: uuid.UUID) -> Decimal:
        """Returns held quantity for an instrument (positive for long, 0 for flat)."""
        return self.positions.get(instrument_id, Decimal("0.0000"))


class BaseStrategy(abc.ABC):
    """Abstract base class for all institutional trading strategies."""

    strategy_id: str = "base_strategy"
    strategy_name: str = "Base Strategy"
    version: str = "1.0.0"
    author: str = "Quantitative Research Team"
    description: str = "Abstract base strategy"
    category: StrategyCategory = StrategyCategory.custom
    required_lookback: int = 50
    default_parameters: dict[str, Any] = {}

    def __init__(
        self,
        params: dict[str, Any] | None = None,
        parameter_snapshot_id: uuid.UUID | None = None,
    ):
        raw_params = {**self.default_parameters, **(params or {})}
        self.params = self.validate_parameters(raw_params)
        self.parameter_snapshot_id = parameter_snapshot_id

    @classmethod
    def get_metadata(cls) -> StrategyMetadata:
        """Return immutable strategy metadata specification."""
        return StrategyMetadata(
            strategy_id=cls.strategy_id,
            name=cls.strategy_name,
            version=cls.version,
            author=cls.author,
            description=cls.description,
            category=cls.category,
            required_lookback=cls.required_lookback,
            default_parameters=cls.default_parameters,
            parameter_schema=cls.get_parameter_schema(),
            min_history_required=cls.required_lookback,
        )

    @classmethod
    def get_parameter_schema(cls) -> dict[str, Any]:
        """Return JSON Schema for parameter validation and frontend rendering."""
        schema = {}
        for key, val in cls.default_parameters.items():
            schema[key] = {
                "type": type(val).__name__,
                "default": val,
            }
        return schema

    @classmethod
    def validate_parameters(cls, params: dict[str, Any]) -> dict[str, Any]:
        """Validate and cast parameter values against constraints.
        Override in subclasses to enforce specific bounds.
        """
        return params

    def initialize(self, context: StrategyContext) -> None:
        """Lifecycle hook called once prior to strategy evaluation."""
        pass

    @abc.abstractmethod
    def on_bar(self, bar: HistoricalBar, context: StrategyContext) -> list[TradingSignal]:
        """Pure evaluation hook executed sequentially for every market bar.

        Must return a list of TradingSignals. Must NOT mutate any portfolio state.
        """
        pass

    def on_fill(self, fill_data: dict[str, Any], context: StrategyContext) -> None:
        """Lifecycle notification when an order generated by this strategy fills."""
        pass

    def on_position_update(self, position_data: dict[str, Any], context: StrategyContext) -> None:
        """Lifecycle notification when portfolio positions change."""
        pass

    def create_signal(
        self,
        bar: HistoricalBar,
        signal_type: SignalType,
        direction: SignalDirection,
        confidence: float,
        target_quantity: Decimal,
        target_weight: Decimal | None = None,
        entry_price: Decimal | None = None,
        stop_loss: Decimal | None = None,
        take_profit: Decimal | None = None,
        expected_holding_period: str = "intraday",
        market_regime: MarketRegime = MarketRegime.unknown,
        supporting_indicators: dict[str, Any] | None = None,
        explanation: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> TradingSignal:
        """Helper factory method to construct a fully attributed, immutable TradingSignal."""
        calc_entry = entry_price if entry_price is not None else bar.close
        rr_ratio = None
        if stop_loss is not None and take_profit is not None and calc_entry is not None:
            risk = abs(calc_entry - stop_loss)
            reward = abs(take_profit - calc_entry)
            if risk > Decimal("0.0000"):
                rr_ratio = (reward / risk).quantize(Decimal("0.01"))

        return TradingSignal(
            signal_id=uuid.uuid4(),
            strategy_id=self.strategy_id,
            strategy_version=self.version,
            parameter_snapshot_id=self.parameter_snapshot_id,
            instrument_id=bar.instrument_id,
            symbol=bar.symbol,
            timestamp=bar.timestamp,
            signal_type=signal_type,
            direction=direction,
            confidence=max(0.0, min(1.0, float(confidence))),
            target_quantity=target_quantity,
            target_weight=target_weight,
            entry_price=calc_entry,
            stop_loss=stop_loss,
            take_profit=take_profit,
            risk_reward_ratio=rr_ratio,
            expected_holding_period=expected_holding_period,
            signal_expiry=None,
            generation_time=datetime.now(timezone.utc),
            market_regime=market_regime,
            supporting_indicators=supporting_indicators or {},
            human_readable_explanation=explanation,
            metadata=metadata or {},
        )
