"""Domain Schemas & Signal Definitions for Strategy Engine."""
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
import uuid

from pydantic import BaseModel, ConfigDict, Field

from app.domains.strategies.enums import (
    MarketRegime,
    SignalDirection,
    SignalType,
    StrategyCategory,
    StrategyStatus,
)


class StrategyMetadata(BaseModel):
    """Immutable metadata and documentation for a registered strategy."""
    model_config = ConfigDict(frozen=True)

    strategy_id: str
    name: str
    version: str = "1.0.0"
    author: str = "Quantitative Research Team"
    description: str
    category: StrategyCategory
    supported_markets: list[str] = Field(default_factory=lambda: ["NSE", "BSE", "NFO"])
    required_lookback: int = 50
    required_indicators: list[str] = Field(default_factory=list)
    parameter_schema: dict[str, Any] = Field(default_factory=dict)
    default_parameters: dict[str, Any] = Field(default_factory=dict)
    min_history_required: int = 30


class TradingSignal(BaseModel):
    """Immutable, explainable trading signal emitted by a strategy."""
    model_config = ConfigDict(frozen=True)

    signal_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    strategy_id: str
    strategy_version: str = "1.0.0"
    parameter_snapshot_id: uuid.UUID | None = None
    instrument_id: uuid.UUID
    symbol: str
    timestamp: datetime
    signal_type: SignalType
    direction: SignalDirection
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    target_quantity: Decimal = Decimal("0.0000")
    target_weight: Decimal | None = None
    entry_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    risk_reward_ratio: Decimal | None = None
    expected_holding_period: str = "intraday"
    signal_expiry: datetime | None = None
    generation_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    market_regime: MarketRegime = MarketRegime.unknown
    supporting_indicators: dict[str, Any] = Field(default_factory=dict)
    human_readable_explanation: str = "Signal generated by strategy rules."
    metadata: dict[str, Any] = Field(default_factory=dict)


class ParameterSnapshotSchema(BaseModel):
    """Schema for an immutable versioned parameter snapshot."""
    snapshot_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    strategy_id: str
    version: str
    parameters: dict[str, Any]
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class StrategyInstanceCreateRequest(BaseModel):
    """Request payload to create a new strategy execution instance."""
    strategy_id: str
    portfolio_id: uuid.UUID
    custom_name: str | None = None
    parameters: dict[str, Any] = Field(default_factory=dict)


class StrategyInstanceResponse(BaseModel):
    """Response payload for a strategy instance."""
    instance_id: uuid.UUID
    strategy_id: str
    portfolio_id: uuid.UUID
    custom_name: str
    version: str
    status: StrategyStatus
    parameters: dict[str, Any]
    parameter_snapshot_id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class SignalEvaluationRequest(BaseModel):
    """Request to evaluate a strategy on a specific bar or historical window."""
    strategy_id: str
    instrument_id: uuid.UUID
    symbol: str
    portfolio_id: uuid.UUID
    parameters: dict[str, Any] = Field(default_factory=dict)


class ParameterSnapshotCreate(BaseModel):
    """Payload to create a parameter snapshot."""
    parameters: dict[str, Any]
    description: str = ""
    created_by: str = "system"


class ParameterSnapshotResponse(BaseModel):
    """Response for parameter snapshot."""
    id: uuid.UUID
    strategy_id: str
    version: str
    parameters: dict[str, Any]
    description: str = ""
    created_by: str = "system"
    created_at: datetime


class StrategyCreate(BaseModel):
    """Payload to register a new strategy."""
    strategy_id: str
    name: str
    version: str = "1.0.0"
    category: StrategyCategory
    description: str = ""
    default_parameters: dict[str, Any] = Field(default_factory=dict)


class StrategyUpdate(BaseModel):
    """Payload to update strategy definition."""
    name: str | None = None
    description: str | None = None
    is_active: bool | None = None


class StrategyParameterValidationRequest(BaseModel):
    """Payload to validate parameters."""
    parameters: dict[str, Any]


class StrategyParameterValidationResponse(BaseModel):
    """Response containing parameter validation results."""
    is_valid: bool
    validated_parameters: dict[str, Any] = Field(default_factory=dict)
    errors: list[str] = Field(default_factory=list)

