"""PostgreSQL Dialect and DDL compilation validation tests for Trading OMS."""
import uuid
from decimal import Decimal
import pytest
from sqlalchemy import select
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from app.domains.trading.models import (
    Fill,
    Order,
    OrderDecision,
    OrderEventLog,
    Portfolio,
    Position,
    PositionLot,
    Transaction,
)


def test_postgresql_ddl_compilation_all_trading_tables():
    """Verify that all trading domain tables compile cleanly to native PostgreSQL DDL."""
    pg_dialect = postgresql.dialect()

    tables = [
        Portfolio.__table__,
        Order.__table__,
        OrderDecision.__table__,
        Fill.__table__,
        Position.__table__,
        PositionLot.__table__,
        Transaction.__table__,
        OrderEventLog.__table__,
    ]

    for table in tables:
        ddl = str(CreateTable(table).compile(dialect=pg_dialect))
        assert table.name in ddl
        # Verify primary key contains UUID
        assert "UUID" in ddl or "uuid" in ddl.lower()


def test_postgresql_column_types_and_precision():
    """Verify exact column types generated by PostgreSQL dialect."""
    pg_dialect = postgresql.dialect()

    # 1. Orders table
    orders_ddl = str(CreateTable(Order.__table__).compile(dialect=pg_dialect))
    assert "NUMERIC(20, 4)" in orders_ddl
    assert "NUMERIC(18, 4)" in orders_ddl
    assert "TIMESTAMP WITH TIME ZONE" in orders_ddl
    assert "UUID" in orders_ddl

    # 2. Transactions table
    txn_ddl = str(CreateTable(Transaction.__table__).compile(dialect=pg_dialect))
    assert "NUMERIC(20, 4)" in txn_ddl
    assert "TIMESTAMP WITH TIME ZONE" in txn_ddl

    # 3. PositionLot table
    lot_ddl = str(CreateTable(PositionLot.__table__).compile(dialect=pg_dialect))
    assert "NUMERIC(20, 4)" in lot_ddl
    assert "NUMERIC(18, 4)" in lot_ddl

    # 4. OrderEventLog table
    log_ddl = str(CreateTable(OrderEventLog.__table__).compile(dialect=pg_dialect))
    assert "JSON" in log_ddl or "json" in log_ddl.lower()


def test_postgresql_for_update_row_locking_compilation():
    """Verify that pessimistic locking compiles to SELECT ... FOR UPDATE in PostgreSQL."""
    pg_dialect = postgresql.dialect()
    order_id = uuid.uuid4()

    stmt = select(Order).where(Order.id == order_id).with_for_update()
    compiled_sql = str(stmt.compile(dialect=pg_dialect, compile_kwargs={"literal_binds": True}))
    assert "FOR UPDATE" in compiled_sql

    port_stmt = select(Portfolio).where(Portfolio.id == order_id).with_for_update()
    compiled_port_sql = str(port_stmt.compile(dialect=pg_dialect, compile_kwargs={"literal_binds": True}))
    assert "FOR UPDATE" in compiled_port_sql


def test_trading_schema_constraints_and_indexes():
    """Verify all unique constraints and indexes are registered on SQLAlchemy metadata."""
    # Check Position Unique Constraint
    pos_table = Position.__table__
    unique_names = [u.name for u in pos_table.constraints if hasattr(u, "name") and u.name]
    assert "uq_portfolio_instrument_product" in unique_names

    # Check composite indexes
    order_idx_names = [idx.name for idx in Order.__table__.indexes]
    assert "ix_orders_portfolio_status" in order_idx_names

    txn_idx_names = [idx.name for idx in Transaction.__table__.indexes]
    assert "ix_transactions_portfolio_created" in txn_idx_names

    lot_idx_names = [idx.name for idx in PositionLot.__table__.indexes]
    assert "ix_position_lots_active" in lot_idx_names

    event_idx_names = [idx.name for idx in OrderEventLog.__table__.indexes]
    assert "ix_event_log_agg_ver" in event_idx_names
