"""Domain Schemas and Immutable Value Objects for Portfolio Construction Engine."""
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any
import uuid

from pydantic import BaseModel, ConfigDict, Field

from app.domains.portfolio.enums import (
    AllocationPolicyType,
    ArbitrationMethod,
    CandidateOrderStatus,
    OptimizationObjective,
    RankingMethod,
    SizingMethod,
)
from app.domains.strategies.enums import SignalDirection, SignalType
from app.domains.strategies.schemas import TradingSignal
from app.domains.trading.enums import OrderSide, ProductType


class PositionSnapshot(BaseModel):
    """Immutable snapshot of an open portfolio position."""
    model_config = ConfigDict(frozen=True)

    instrument_id: uuid.UUID
    symbol: str
    quantity: Decimal
    average_entry_price: Decimal
    current_market_price: Decimal
    current_notional: Decimal
    current_weight: Decimal
    unrealized_pnl: Decimal
    realized_pnl: Decimal
    sector: str = "General"
    strategy_id: str | None = None


class PortfolioSnapshot(BaseModel):
    """Immutable, complete point-in-time state of the portfolio.
    Eliminates all database lookups during mathematical optimization.
    """
    model_config = ConfigDict(frozen=True)

    portfolio_id: uuid.UUID
    timestamp: datetime
    cash_balance: Decimal
    reserved_cash: Decimal = Decimal("0.00")
    total_equity: Decimal
    positions: dict[uuid.UUID, PositionSnapshot] = Field(default_factory=dict)
    sector_exposures: dict[str, Decimal] = Field(default_factory=dict)
    strategy_exposures: dict[str, Decimal] = Field(default_factory=dict)
    current_weights: dict[uuid.UUID, Decimal] = Field(default_factory=dict)
    unrealized_pnl: Decimal = Decimal("0.00")
    realized_pnl: Decimal = Decimal("0.00")
    volatilities: dict[uuid.UUID, Decimal] = Field(default_factory=dict)
    correlations: dict[tuple[uuid.UUID, uuid.UUID], Decimal] = Field(default_factory=dict)
    historical_volumes: dict[uuid.UUID, Decimal] = Field(default_factory=dict)


class SignalRankingScore(BaseModel):
    """Normalized scoring output for an individual trading signal."""
    model_config = ConfigDict(frozen=True)

    signal_id: uuid.UUID
    instrument_id: uuid.UUID
    symbol: str
    strategy_id: str
    direction: SignalDirection
    composite_score: float = Field(ge=0.0, le=1.0)
    rank: int = Field(ge=1)
    feature_breakdown: dict[str, float] = Field(default_factory=dict)
    explanation: str


class ArbitrationDecision(BaseModel):
    """Immutable record of multi-signal conflict resolution for a single instrument."""
    model_config = ConfigDict(frozen=True)

    instrument_id: uuid.UUID
    symbol: str
    winning_side: OrderSide | None  # None if neutralized
    selected_signals: list[uuid.UUID]
    discarded_signals: list[uuid.UUID]
    blended_confidence: float
    blended_entry_price: Decimal | None
    blended_stop_loss: Decimal | None
    blended_take_profit: Decimal | None
    conflict_type: str  # e.g. "BUY_VS_SELL", "SAME_SIDE_CONSENSUS", "NO_CONFLICT"
    resolution_method: ArbitrationMethod
    reason: str


class TransactionCostEstimate(BaseModel):
    """Estimated frictional transaction costs before trade dispatch."""
    model_config = ConfigDict(frozen=True)

    estimated_brokerage: Decimal = Decimal("0.0000")
    estimated_stt: Decimal = Decimal("0.0000")
    estimated_exchange_turnover: Decimal = Decimal("0.0000")
    estimated_gst: Decimal = Decimal("0.0000")
    estimated_sebi_charges: Decimal = Decimal("0.0000")
    estimated_stamp_duty: Decimal = Decimal("0.0000")
    estimated_slippage: Decimal = Decimal("0.0000")
    total_estimated_costs: Decimal = Decimal("0.0000")


class CandidateOrder(BaseModel):
    """Immutable, explainable Value Object generated by the Portfolio Construction Engine.
    Strictly forwarded to Pre-Trade Risk Engine; NEVER directly executed.
    """
    model_config = ConfigDict(frozen=True)

    candidate_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    plan_id: uuid.UUID
    portfolio_id: uuid.UUID
    instrument_id: uuid.UUID
    symbol: str
    side: OrderSide
    product_type: ProductType = ProductType.cnc
    quantity: Decimal
    target_weight: Decimal
    current_weight: Decimal = Decimal("0.0000")
    estimated_price: Decimal
    estimated_notional: Decimal
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    confidence: float
    expected_return: Decimal | None = None
    expected_risk: Decimal | None = None
    risk_reward_ratio: Decimal | None = None
    strategy_sources: list[str]
    signal_sources: list[uuid.UUID]
    ranking_score: float
    ranking_breakdown: dict[str, float] = Field(default_factory=dict)
    sizing_method: SizingMethod
    sizing_breakdown: dict[str, Any] = Field(default_factory=dict)
    transaction_costs: TransactionCostEstimate = Field(default_factory=TransactionCostEstimate)
    reasoning: str
    explainability_trace: dict[str, Any] = Field(default_factory=dict)
    status: CandidateOrderStatus = CandidateOrderStatus.generated
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class PortfolioConstructionConfig(BaseModel):
    """Complete, versioned configuration parameters for the Portfolio Construction Engine."""
    model_config = ConfigDict(frozen=True)

    version: str = "1.0.0"
    reserve_cash_pct: Decimal = Decimal("0.0500")  # Default 5% reserve
    max_portfolio_exposure: Decimal = Decimal("0.9500")
    max_instrument_weight: Decimal = Decimal("0.1000")  # Max 10% per asset
    max_sector_weight: Decimal = Decimal("0.2500")      # Max 25% per sector
    max_strategy_weight: Decimal = Decimal("0.3500")    # Max 35% per strategy
    max_positions: int = 10
    rebalance_deadband_pct: Decimal = Decimal("0.0150") # 1.5% deadband to prevent churn
    min_daily_volume: Decimal = Decimal("10000")
    ranking_method: RankingMethod = RankingMethod.multi_factor_linear
    ranking_weights: dict[str, float] = Field(default_factory=lambda: {
        "confidence": 0.35,
        "risk_reward": 0.25,
        "freshness": 0.20,
        "historical_sharpe": 0.20,
    })
    arbitration_method: ArbitrationMethod = ArbitrationMethod.net_confidence_weighted
    arbitration_neutral_threshold: float = 0.10
    allocation_policy: AllocationPolicyType = AllocationPolicyType.score_proportional
    sizing_method: SizingMethod = SizingMethod.volatility_adjusted
    risk_per_trade_pct: Decimal = Decimal("0.0100")     # 1% risk per trade
    atr_multiplier: Decimal = Decimal("2.0")
    half_kelly_damping: float = 0.50
    signal_ttl_seconds: int = 3600                       # 1 hour default


class PortfolioConstructionPlanResponse(BaseModel):
    """API and Service response representing a complete portfolio construction execution."""
    plan_id: uuid.UUID
    portfolio_id: uuid.UUID
    timestamp: datetime
    allocation_policy: AllocationPolicyType
    sizing_method: SizingMethod
    total_equity: Decimal
    cash_allocated: Decimal
    reserve_cash: Decimal
    total_candidates: int
    candidate_orders: list[CandidateOrder]
    arbitration_decisions: list[ArbitrationDecision]
    summary_metrics: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime


class PortfolioEvaluationRequest(BaseModel):
    """Request payload to evaluate strategy signals against a portfolio."""
    portfolio_id: uuid.UUID
    signals: list[TradingSignal]
    config: PortfolioConstructionConfig | None = None
    current_prices: dict[uuid.UUID, Decimal] | None = None
    volatilities: dict[uuid.UUID, Decimal] | None = None
    sectors: dict[uuid.UUID, str] | None = None


class PortfolioEngineMetricsResponse(BaseModel):
    """Performance telemetry and optimization statistics."""
    total_plans_executed: int
    total_candidate_orders_generated: int
    avg_optimization_latency_ms: float
    avg_ranking_latency_ms: float
    avg_candidate_count_per_plan: float
    arbitration_conflict_count: int
    last_evaluation_timestamp: datetime | None
